name: Mirror to Gitee Repo

on: [ push, delete, create ]

jobs:
   git-mirror:
    runs-on: ubuntu-latest
    steps:
     - name: Configure Private Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
      - name: Push Mirror
        env:
          SOURCE_REPO: 'https://github.com/lavender-juan/newcosbrowser.git'
          DESTINATION_REPO: 'git@gitee.com:juan-lavender/newcosbrowser.git'
          DESTINATION_REPO: 'https://gitee.com/juan-lavender/newcosbrowser.git'
        run: |
          git clone --mirror "$SOURCE_REPO" && cd `basename "$SOURCE_REPO"`
          git remote set-url --push origin "$DESTINATION_REPO"
