name: Mirror to Gitee Repo

on: [ push, delete, create ]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Push Mirror
        env:
          SOURCE_REPO: 'https://github.com/lavender-juan/cosbrowser.git'
          DESTINATION_REPO: 'https://github.com/lavender-juan/cosbrowser.git'
        run: |
          git clone --mirror "$SOURCE_REPO" && cd `basename "$SOURCE_REPO"`
          git remote set-url --push origin "$DESTINATION_REPO"
          git fetch -p origin
          git for-each-ref --format 'delete %(refname)' refs/pull | git update-ref --stdin
          git push --mirror
